### ISSUE TITLE
Device connected to wifi but all ports are closed

### ISSUE THREAD

**Issue by vremy** [millheat/Generation_3_REST_API#9]
I bought a Generation 3 1200W panel heater which is connected to my WiFi network but all ports are closed so i cannot used this api to control it.

I downloaded the Android Mill app to configure the device. When configuring the device in the app i selected my WiFi network and i clicked on Advanced mode and selected the option **Enable local API but with no cloud connection**. I finished up the setup through the mill app and i am able to control the panel heater through the app. But when i want to control the heater through the API i get connection refused responses. 

I did a nmap scan on my WiFi network to locate the panel heater. I confirmed it was connected to my WiFi network because the mac address from the device found by nmap corresponds with the mac address that is displayed in the Android Mill app. But all ports on the device where closed which explains why i was unable to control the panel heater through the API.

The strange thing is that i chose **Enable local API but with no cloud connection** during the setup of the device. But when i disconnect my phone from the WiFi network i am still able to control the device and set the temperature. So despite having selected the option to not use a cloud connection it still has setup a cloud connection. 

I have no clue how to fix this, i already repeated the setup of the device to make sure i did configure it right but i get the same results. The Reason i want to control this through the API and not the Android app is because i want to integrate this panel heater in Home Assistant.

```
Device: Mill PA1200WIFIB
Android APP Version: 4.3.8
```

**Comment by millheat** [comment]
Hi Vremy, 

This is odd, when selecting Enable local APOI but with no cloud connection it should not allow any control using the Mill Norway app,since the device is not on the cloud but only locally on your network. 

You can also configure the ap in a very simple way, so please try this and see if makes any difference : 
1: Reset the heater first 
2: Press and hold the Wi-Fi button until you see AP on the display , the release the button 
3: The heater is now in AP mode, you can connect to the heater and it will take you to its portal 
4: There you can connect to WiFi and select Enable Local API but with no cloud connection 
5: Check to see if it works now and if it does not please send us more details on what commands you are trying to use with full details so that we can look into this for you.

**Comment by vremy** [comment]
Thank you, following your steps i got it working! The first try it didn't work because i filled in the SSID and password immediately without scanning for networks. The second time i first scanned the networks, chose the network which automatically filled in the SSID and then i filled in the password myself and then it was connected to my network with API support.
